### ISSUE TITLE
(auth) Missing Form Feedback

### ISSUE THREAD

**Issue by swedneck** [cr4yfish/learn-better#3]
browser: firefox 131.0.3

This prevents me from logging in, it just keeps redirecting to the main page without actually logging me in when i submit my credentials.

![image](https://github.com/user-attachments/assets/4b0818de-296d-4aa7-ba5e-d75e841aa4e5)

**Comment by cr4yfish** [comment]
Thanks for the bug report! I'll take a look asap

**Comment by cr4yfish** [comment]
Found the issue.
![image](https://github.com/user-attachments/assets/8d5a745a-9787-4f2a-b1cc-b2f85bcba25a)

Looks like you signed up with a pw thats >72 chars long, for which I didn't code user feedback. Then you tried to log in with "incorrect" user credentials (no acc was created).. for which I again didn't code feedback.

**Comment by cr4yfish** [comment]
I'll code in some popups that'll prevent situations like these. I'll also look into extending the max. pw length.

Lmk if creating a new acc with a shorter password fixes the issue.

**Comment by swedneck** [comment]
> I'll code in some popups that'll prevent situations like these. I'll also look into extending the max. pw length.
> 
> Lmk if creating a new acc with a shorter password fixes the issue.

actually this raises the question of whether users can delete their accounts, you probably want to make sure it's easy to delete accounts and any data associated with the user, so there won't be any problems with regulations like the EU's GDPR

**Comment by cr4yfish** [comment]
Ah shit I totally forgot to add a delete acc button.
Associated data will get removed automatically in the Database, since I've used cascade links everywhere where personalized data is.

**Comment by cr4yfish** [comment]
I added a new issue for the Account Delete Button #4 .

The missing feedback went up with the latest version, forgot to mention this issue in the commit message lol.
