### ISSUE TITLE
password length limit issue

### ISSUE THREAD

**Issue by swedneck** [cr4yfish/learn-better#6]
Hi again! Just tried remaking my account and now it says my password is too long despite being at most 72 characters, trying 24 characters worked fine though, and i was now able to make an account and log in.

**Comment by cr4yfish** [comment]
Oh yeah I know the issue.

```
function validatePassword(password: string) {
    return (password.length >= 8 && **password.length < 72**) ? true : undefined;
}
```

Give me a second, I'll fix it, thanks for testing it out!
